name = "e2e"
engineVersion = "v1.0.0-0"

[runtime]
  source = "dang"

[[dependencies]]
  name = "engine-dev"
  source = "github.com/dagger/dagger/.dagger/modules/engine-dev@sdk-ux-module-max"
  pin = "66da6410cbbb992b9adcb42c08d38d5a38f2f05b"
