name = "e2e"
engineVersion = "v1.0.0-0"

[runtime]
  source = "dang"

[[dependencies]]
  name = "dagger-dev"
  source = "github.com/dagger/dagger/.dagger/modules/dagger-dev@a349dcee151e6d33cb7af902cba1af58c468a0b3"
